
message:

  delimiters:
    section: "#"
    value: ":"

  keys:
    full-message-size: "FS"
    package-type: "PT"
    recipient-type: "RT"
    recipient-id: "ID"
    module: "M"
    request-id: "REQ"
    response-type: "RPT"

  packages:
    first-part: "first"
    continuation: "con"
    last-part: "last"
    single-message: "single"

  recipients:
    control-side: "control"
    bot-side: "bot"