
message:

  delimiters:
    section:  "#"
    value:    ":"

  keys:
    full-message-size: "FS"
    package-type:     "PT"
    target-type:      "TT"
    target-id:        "TID"
    target-module:    "TM"
    request-id:       "RID"
    response-type:    "RT"

  packages:
    first-part:     "first"
    continuation:   "con"
    last-part:      "last"
    single-message: "single"

  targets:
    control-side: "control"
    bot-side:     "bot"
    server-side:  "server"